[private]
default: help

# Shows this help message
help:
  @just --list

create-db:

prepare:

migrate:

package-tar:
  #!/usr/bin/env bash
  cargo zigbuild --target aarch64-unknown-linux-musl --release -p achilles-api

  mkdir -p build/usr/bin
  mkdir -p build/etc/init.d
  mkdir -p build/etc/conf.d

  PROJECT_DIR="$(printf $(cd ../../ && pwd))"

  cp -v $PROJECT_DIR/target/aarch64-unknown-linux-musl/release/achilles-api build/usr/bin
  cp res/achilles-api.initd build/etc/init.d/achilles-api
  cp res/achilles-api.confd build/etc/conf.d/achilles-api
  chmod 755 build/etc/init.d/achilles-api
  chmod 755 build/usr/bin/achilles-api

  rm *.tar.zst
  tar -cvf - -C build . | zstd -T0 -o achilles-api.tar.zst

dev:
  @bun --bun run dev
